const List<String> sensitiveWords = [
  'đụ má',
  'đm',
  'con cặc',
  'cc',
  'lồn',
  'cl',
  'cái lồn',
  'địt',
  'đéo',
  'khốn nạn',
  'cặc',
  'cu',
  'buồi',
  'mồm',
  'đụ',
  'địt mẹ',
  'đụ má mày',
  'lồn địt',
  'thằng điếm',
  'lồn cặc',
  'chịch',
  'đĩ',
  'địt nhau',
  'đụ má con',
  'mẹ mày',
  'mày bố',
  'mẹ mày đĩ',
  'thằng đần',
  'đồ chó',
  'lồn con mẹ',
  'mẹ đĩ',
  'lồn chó',
  'chó đẻ',
  'đồ chó chết',
  'mẹ đẻ',
  'địt lồn',
  'cặc chó',
  'thằng điên',
  'má con mẹ',
  'lồn bố',
  'mẹ chó',
  'đụ mẹ mày',
  'lồn chó chết',
  'chó điên',
  'mẹ kế',
  'đụ mẹ',
  'thằng mày',
  'đồ mồm',
  'lồn chó đẻ',
  'địt mẹ mày',
  'địt mẹ mày chết',
  'mày chết',
  'đụ má mày chết',
  'lồn mẹ mày',
  'lồn đĩ',
  'địt mẹ mày',
  'mẹ đĩ mày',
  'đụ mẹ mày chết',
  'lồn mẹ mày chết',
  'mày điên',
  'địt mẹ mày đi',
  'lồn mẹ mày đĩ',
  'mẹ mày chết',
  'đụ má mày đi',
  'lồn chó mẹ mày',
  'mẹ mày địt',
  'má mày',
  'lồn bố mày',
  'đụ má mày địt',
  'đụ mẹ chết',
  'mày lồn',
  'mẹ chết mày',
  'mẹ đẻ mày',
  'lồn mày',
  'mẹ bây',
  'má chết mày',
  'mẹ mày lồn',
  'mẹ đéo',
  'chó lồn',
  'lồn con chó',
  'lồn mày chết',
  'lồn địt mẹ',
  'đụ má mày lồn',
  'má mày đụ',
  'má mày địt',
  'mẹ lồn mày',
  'mẹ mày địt',
  'mẹ lồn địt',
  'lồn mày địt',
  'mẹ đĩ mày lồn',
  'má đĩ mày',
  'lồn mẹ mày chết',
  'má mày đụ mẹ',
  'đụ má mày chó',
  'má chó',
  'đụ mẹ con',
  'mẹ mày đi',
  'mẹ điếm',
  'lồn chó chết mày',
  'lồn mẹ mày đi',
  'má mày lồn',
  'lồn mẹ mày địt',
  'má chết',
  'má mày đi',
  'đụ má mày lồn địt',
  'lồn đéo',
  'má mày địt mẹ',
  'lồn mẹ mày đụ',
  'má mày địt mẹ',
  'đụ má mày con',
  'má mày chết',
  'má mày đụ',
  'lồn con chó',
  'mẹ mày đụ',
  'má mày lồn chó',
  'mẹ lồn mày chết',
  'lồn mẹ mày đi',
  'lồn mẹ mày đĩ',
  'má mày điếm',
  'má mày đụ má',
  'lồn con mẹ mày',
  'đụ má mày đĩ',
  'má mày địt',
  'lồn chó đụ',
  'má mày địt mẹ',
  'lồn mẹ mày đĩ',
  'đụ mẹ mày lồn',
  'má mày chết mày',
  'đụ mẹ con mẹ mày',
  'lồn mẹ mày lồn',
  'má mày đéo',
  'má chó mẹ mày',
  'má chó con',
  'má mày địt mày',
  'lồn con mày',
  'má mày địt mẹ mày',
  'má đĩ',
  'đụ má mày đụ',
  'má mày chó',
  'lồn mẹ mày chó',
  'má mày đĩ chết',
  'lồn mẹ con mẹ mày',
  'mẹ mày chết mẹ mày',
  'đụ mẹ mày đụ má',
  'lồn đít',
  'má mày đụ mẹ',
  'má đéo',
  'đụ má mày đụ má',
  'đụ má mày lồn chó',
  'má mày điếm mẹ',
  'má mày đụ má mày',
  'lồn mẹ mày đéo',
  'má chó mẹ',
  'đụ mẹ mày lồn mẹ',
  'lồn địt mẹ mày',
  'lồn mẹ chó',
  'đụ má mày con chó',
  'má mày chết chết',
  'đụ má mày địt',
  'đụ má mày đít',
  'đụ má mày đụ má',
  'đụ má mày mày',
  'má mày mày',
  'má mày lồn chết',
  'má mày đụ chết',
  'má chó mẹ mày',
  'đụ má mày chết mày',
  'má mày mẹ mày',
  'má mày chết mẹ',
  'lồn mẹ chó mày',
  'má mày đụ má mày',
  'má mày địt mẹ mày',
  'lồn chết mẹ mày',
  'đụ má mày lồn đít',
  'má mày lồn đéo',
  'đụ má mày lồn mày',
  'lồn mẹ mày mày',
  'má mày chó mày',
  'má mày lồn đĩ',
  'lồn mẹ mày chó',
  'má mày đụ má mày',
  'má mày chết chết',
  'má mày đụ đéo',
  'má mày đụ má mẹ',
  'lồn mẹ mày đĩ',
  'má mày đụ má mẹ',
  'má mày đéo mẹ',
  'má mày lồn đụ',
  'lồn đéo mẹ mày',
  'lồn mẹ chó đéo',
  'má mày địt chết',
  'lồn đít mẹ mày',
  'má mày lồn chó mẹ',
  'fuck',
  'cunt',
  'dickhead',
  'asshole',
  'bastard',
  'whore',
  'slut',
  'motherfucker',
  'cocksucker',
  'pussy',
  'blowjob',
  'handjob',
  'tits',
  'anal',
  'orgasm',
  'dildo',
  'erection',
  'ejaculation',
  'kinky',
  'fetish',
  'bitch',
  'screw',
  'suck',
  'wank',
  'vagina',
  'penis',
  'testicles',
  'masturbate',
  'fornicate',
  'nipples',
  'buttplug',
  'rimjob',
  'clitoris',
  'threesome',
  'orgy',
  'golden shower',
  'sexting',
  'cybersex',
  'prostitute',
  'escort',
  'nude',
  'condom',
  'pubic hair',
  'incest',
  'pedophile',
  'bestiality',
  'anus',
  'douchebag',
  'erotic',
  'sex toy',
  'milf',
  'squirting',
  'cock',
  'vulva',
  'fisting',
  'hentai',
  'naked',
  'rape',
  'sex slave',
  'virgin',
  'vibrator',
  'gonorrhea',
  'herpes',
  'syphilis',
  'clap',
  'chlamydia',
  'HPV',
  'HIV',
  'AIDS',
  'STD',
  'contraception',
  'fellation',
  'muff',
  'nudism',
  'porn',
  'pubes',
  'pubic',
  'sodomy',
  'voyeur',
  'tit',
  'milf',
  'erect',
  'strapon',
  'bisexual',
  'queer',
  'homosexual',
  'lesbian',
  'transgender',
  'genderqueer',
  'pansexual',
  'asexual',
  'intersex',
  'genderfluid',
  'grindr',
  'tinder',
  'bumsex',
  'cougar',
  'shemale',
  'foreskin',
  'g-spot',
  'camgirl',
  'striptease',
  'kamasutra',
  'playboy',
  'rimming',
  'twink',
  'gaydar',
  'leatherman',
  'bear',
  'muffdiving',
  'tribadism',
  'furry',
  'hotwife',
  'gloryhole',
  'scat',
  'pegging',
  'ménage à trois',
  'swinger',
  'cumshot',
  'blue balls',
  'knobbing',
  'butt plug',
  'shibari',
  'teabagging',
  'pearl necklace',
  'nuru',
  'tantra',
  'spanking',
  'bukkake',
  'midget',
  'watersports',
  'dogging',
  'fist',
  'jerk off',
  'skank',
  'deepthroat',
  'cuckold',
  'nympho',
  'facial',
  'titjob',
  'sexercise',
  'sextoys',
  'fingerbang',
  'cameltoe',
  'throating',
  'futanari',
  'camwhore',
  'hardcore',
  'cum',
  'gokkun',
  'hump',
  'panties',
  'bondage',
  'scissoring',
  'bodystocking',
  'fellatio',
  'labia',
  'doggystyle',
  'creampie',
  'cumming',
  'blowbang',
  'cummy',
  'facial',
  'busty',
  'titty',
  'titties',
  'creampie',
  'femdom',
  'domme',
  'mistress',
  'slave',
  'chastity',
  'ballbusting',
  'breastfeeding',
  'cuck',
  'pegging',
  'panty',
  'gangbang',
  'kink',
  'naughty',
  'twat',
  'wet',
  'ass',
  'boob',
  'booty',
  'gagging',
  'jizz',
  'penetration',
  'boob',
  'boner',
  'arousal',
  'foreplay',
  'erogenous',
  'stimulate',
  'pleasure',
  'strip',
  'striptease',
  'undress',
  'lingerie',
  'bra',
  'thong',
  'braless',
  'pantyhose',
  'stocking',
];
